weights:
  weight_mode: simple
  
noise: False  # specify if simulation should be run with or without noise
sampling_rate: 5.  # sampling rate in GHz used internally in the simulation. At the end the waveforms will be downsampled to the sampling rate specified in the detector description
  
speedup:
  minimum_weight_cut: 1.e-5
  delta_C_cut: 0.698  # 40 degree

propagation:
  ice_model: ARAsim_southpole
  
signal:
  model: Alvarez2000
  
trigger:
  noise_temperature: 300  # in Kelvin
  bandwidth: null  # null or floaat in GHz (the effective bandwidth. It is used to calculate the Vrms from the noise temperature. If None, the bandwidth is calculated from the sampling rate assuming that the bandwidth is 0Hz to the Nyquist frequency
  